[package]
name = "newton-core"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
newton-cpu = { workspace = true }
newton-devices = { workspace = true }
newton-utils = { workspace = true }
newton-m68k = { workspace = true }

anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
parking_lot = { workspace = true }
byteorder = { workspace = true }
memmap2 = { workspace = true }
