// NewtonEmu - PowerPC Macintosh Emulator
// Copyright (C) 2026 NewtonEmu Contributors
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

//! Memory callback functions for JIT code
//!
//! These functions provide memory access for JIT-compiled code.
//! They are called from native code generated by Cranelift.

use crate::{MemoryInterface, Registers};
use std::mem;

/// Register state passed to/from JIT code
/// This must match the layout expected by the JIT compiler
#[repr(C)]
pub struct JitRegisters {
    /// General Purpose Registers (r0-r31)
    pub gpr: [u32; 32],
    
    /// Program Counter
    pub pc: u32,
    
    /// Link Register
    pub lr: u32,
    
    /// Count Register
    pub ctr: u32,
    
    /// Condition Register (packed)
    pub cr: u32,
    
    /// XER Register (packed)
    pub xer: u32,
}

impl JitRegisters {
    /// Create from CPU registers
    pub fn from_registers(regs: &Registers) -> Self {
        Self {
            gpr: regs.gpr,
            pc: regs.pc,
            lr: regs.lr,
            ctr: regs.ctr,
            cr: regs.cr.bits(),
            xer: regs.xer.bits(),
        }
    }
    
    /// Write back to CPU registers
    pub fn write_to_registers(&self, regs: &mut Registers) {
        regs.gpr = self.gpr;
        regs.pc = self.pc;
        regs.lr = self.lr;
        regs.ctr = self.ctr;
        regs.cr = crate::registers::ConditionRegister::from_bits_truncate(self.cr);
        regs.xer = crate::registers::Xer::from_bits_truncate(self.xer);
    }
}

/// Context structure passed to JIT code
#[repr(C)]
pub struct JitContext {
    /// Fat pointer to memory interface stored as two raw pointers
    memory_data: *mut (),
    memory_vtable: *mut (),
    
    /// Pointer to register state
    registers: *mut JitRegisters,
}

impl JitContext {
    /// Create a new JIT context
    pub fn new(memory: &dyn MemoryInterface, registers: &mut JitRegisters) -> Self {
        // Convert trait object reference to raw parts
        let fat_ptr: *const dyn MemoryInterface = memory;
        let (data, vtable) = unsafe {
            mem::transmute::<*const dyn MemoryInterface, (*mut (), *mut ())>(fat_ptr)
        };
        
        Self {
            memory_data: data,
            memory_vtable: vtable,
            registers,
        }
    }
    
    /// Get memory interface from context
    unsafe fn get_memory(&self) -> &dyn MemoryInterface {
        unsafe {
            let fat_ptr = mem::transmute::<(*mut (), *mut ()), *const dyn MemoryInterface>(
                (self.memory_data, self.memory_vtable)
            );
            &*fat_ptr
        }
    }
    
    /// Get register state from context
    pub unsafe fn get_registers(&mut self) -> &mut JitRegisters {
        unsafe { &mut *self.registers }
    }
}

/// Read a 32-bit word from memory (called from JIT code)
#[unsafe(no_mangle)]
pub unsafe extern "C" fn jit_memory_read_u32(ctx: *mut JitContext, addr: u32) -> u32 {
    if ctx.is_null() {
        tracing::error!("JIT memory read with null context");
        return 0;
    }
    
    unsafe {
        let ctx = &mut *ctx;
        match ctx.get_memory().read_u32(addr) {
            Ok(value) => value,
            Err(e) => {
                tracing::error!("JIT memory read error at 0x{:08X}: {}", addr, e);
                0
            }
        }
    }
}

/// Write a 32-bit word to memory (called from JIT code)
#[unsafe(no_mangle)]
pub unsafe extern "C" fn jit_memory_write_u32(ctx: *mut JitContext, addr: u32, value: u32) {
    if ctx.is_null() {
        tracing::error!("JIT memory write with null context");
        return;
    }
    
    unsafe {
        let ctx = &mut *ctx;
        if let Err(e) = ctx.get_memory().write_u32(addr, value) {
            tracing::error!("JIT memory write error at 0x{:08X}: {}", addr, e);
        }
    }
}

/// Read a 16-bit halfword from memory (called from JIT code)
#[unsafe(no_mangle)]
pub unsafe extern "C" fn jit_memory_read_u16(ctx: *mut JitContext, addr: u32) -> u32 {
    if ctx.is_null() {
        tracing::error!("JIT memory read with null context");
        return 0;
    }
    
    unsafe {
        let ctx = &mut *ctx;
        match ctx.get_memory().read_u16(addr) {
            Ok(value) => value as u32,
            Err(e) => {
                tracing::error!("JIT memory read error at 0x{:08X}: {}", addr, e);
                0
            }
        }
    }
}

/// Write a 16-bit halfword to memory (called from JIT code)
#[unsafe(no_mangle)]
pub unsafe extern "C" fn jit_memory_write_u16(ctx: *mut JitContext, addr: u32, value: u32) {
    if ctx.is_null() {
        tracing::error!("JIT memory write with null context");
        return;
    }
    
    unsafe {
        let ctx = &mut *ctx;
        if let Err(e) = ctx.get_memory().write_u16(addr, value as u16) {
            tracing::error!("JIT memory write error at 0x{:08X}: {}", addr, e);
        }
    }
}

/// Read a byte from memory (called from JIT code)
#[unsafe(no_mangle)]
pub unsafe extern "C" fn jit_memory_read_u8(ctx: *mut JitContext, addr: u32) -> u32 {
    if ctx.is_null() {
        tracing::error!("JIT memory read with null context");
        return 0;
    }
    
    unsafe {
        let ctx = &mut *ctx;
        match ctx.get_memory().read_u8(addr) {
            Ok(value) => value as u32,
            Err(e) => {
                tracing::error!("JIT memory read error at 0x{:08X}: {}", addr, e);
                0
            }
        }
    }
}

/// Write a byte to memory (called from JIT code)
#[unsafe(no_mangle)]
pub unsafe extern "C" fn jit_memory_write_u8(ctx: *mut JitContext, addr: u32, value: u32) {
    if ctx.is_null() {
        tracing::error!("JIT memory write with null context");
        return;
    }
    
    unsafe {
        let ctx = &mut *ctx;
        if let Err(e) = ctx.get_memory().write_u8(addr, value as u8) {
            tracing::error!("JIT memory write error at 0x{:08X}: {}", addr, e);
        }
    }
}

