// NewtonEmu - PowerPC Macintosh Emulator
// Copyright (C) 2024 NewtonEmu Contributors
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

//! Memory callback functions for JIT code
//!
//! These functions provide memory access for JIT-compiled code.
//! They are called from native code generated by Cranelift.

use crate::MemoryInterface;
use std::mem;

/// Context structure passed to JIT code
#[repr(C)]
pub struct JitContext {
    /// Fat pointer to memory interface stored as two raw pointers
    memory_data: *mut (),
    memory_vtable: *mut (),
}

impl JitContext {
    /// Create a new JIT context
    pub fn new(memory: &mut dyn MemoryInterface) -> Self {
        // Convert trait object reference to raw parts
        let fat_ptr: *mut dyn MemoryInterface = memory;
        let (data, vtable) = unsafe {
            mem::transmute::<*mut dyn MemoryInterface, (*mut (), *mut ())>(fat_ptr)
        };
        
        Self {
            memory_data: data,
            memory_vtable: vtable,
        }
    }
    
    /// Get memory interface from context
    unsafe fn get_memory(&mut self) -> &mut dyn MemoryInterface {
        unsafe {
            let fat_ptr = mem::transmute::<(*mut (), *mut ()), *mut dyn MemoryInterface>(
                (self.memory_data, self.memory_vtable)
            );
            &mut *fat_ptr
        }
    }
}

/// Read a 32-bit word from memory (called from JIT code)
#[unsafe(no_mangle)]
pub unsafe extern "C" fn jit_memory_read_u32(ctx: *mut JitContext, addr: u32) -> u32 {
    if ctx.is_null() {
        tracing::error!("JIT memory read with null context");
        return 0;
    }
    
    unsafe {
        let ctx = &mut *ctx;
        match ctx.get_memory().read_u32(addr) {
            Ok(value) => value,
            Err(e) => {
                tracing::error!("JIT memory read error at 0x{:08X}: {}", addr, e);
                0
            }
        }
    }
}

/// Write a 32-bit word to memory (called from JIT code)
#[unsafe(no_mangle)]
pub unsafe extern "C" fn jit_memory_write_u32(ctx: *mut JitContext, addr: u32, value: u32) {
    if ctx.is_null() {
        tracing::error!("JIT memory write with null context");
        return;
    }
    
    unsafe {
        let ctx = &mut *ctx;
        if let Err(e) = ctx.get_memory().write_u32(addr, value) {
            tracing::error!("JIT memory write error at 0x{:08X}: {}", addr, e);
        }
    }
}

/// Read a 16-bit halfword from memory (called from JIT code)
#[unsafe(no_mangle)]
pub unsafe extern "C" fn jit_memory_read_u16(ctx: *mut JitContext, addr: u32) -> u32 {
    if ctx.is_null() {
        tracing::error!("JIT memory read with null context");
        return 0;
    }
    
    unsafe {
        let ctx = &mut *ctx;
        match ctx.get_memory().read_u16(addr) {
            Ok(value) => value as u32,
            Err(e) => {
                tracing::error!("JIT memory read error at 0x{:08X}: {}", addr, e);
                0
            }
        }
    }
}

/// Write a 16-bit halfword to memory (called from JIT code)
#[unsafe(no_mangle)]
pub unsafe extern "C" fn jit_memory_write_u16(ctx: *mut JitContext, addr: u32, value: u32) {
    if ctx.is_null() {
        tracing::error!("JIT memory write with null context");
        return;
    }
    
    unsafe {
        let ctx = &mut *ctx;
        if let Err(e) = ctx.get_memory().write_u16(addr, value as u16) {
            tracing::error!("JIT memory write error at 0x{:08X}: {}", addr, e);
        }
    }
}

/// Read a byte from memory (called from JIT code)
#[unsafe(no_mangle)]
pub unsafe extern "C" fn jit_memory_read_u8(ctx: *mut JitContext, addr: u32) -> u32 {
    if ctx.is_null() {
        tracing::error!("JIT memory read with null context");
        return 0;
    }
    
    unsafe {
        let ctx = &mut *ctx;
        match ctx.get_memory().read_u8(addr) {
            Ok(value) => value as u32,
            Err(e) => {
                tracing::error!("JIT memory read error at 0x{:08X}: {}", addr, e);
                0
            }
        }
    }
}

/// Write a byte to memory (called from JIT code)
#[unsafe(no_mangle)]
pub unsafe extern "C" fn jit_memory_write_u8(ctx: *mut JitContext, addr: u32, value: u32) {
    if ctx.is_null() {
        tracing::error!("JIT memory write with null context");
        return;
    }
    
    unsafe {
        let ctx = &mut *ctx;
        if let Err(e) = ctx.get_memory().write_u8(addr, value as u8) {
            tracing::error!("JIT memory write error at 0x{:08X}: {}", addr, e);
        }
    }
}

